/* ─────────────────────────────────────────────
   ДАННЫЕ ПРИГЛАШЕНИЯ — меняйте только здесь
   ───────────────────────────────────────────── */
window.INVITE = {
  name: "Сезим",
  event: "Кыз узатуу тоюна",
  invitedLine: "Сиздерди",
  brideLine: "Сезим кызыбыздын",
  callLine: "Чакырабыз!",
  dateISO: "2026-09-20T17:00:00",
  dateLabel: "20 сентябрь 2026",
  time: "17:00",
  day: "20",
  month: "Сентябрь",
  year: "2026",
  blessing: "Ак ниеттен, жаркын келечекке...",
  photos: {
    shyrdak: "img/shyrdak.png",
    drape: "img/drape.png",
    landscape: "img/landscape.png",
    flowers: "img/gypsophila.png"
  },
  venue: {
    placeLabel: "Ресторан",
    place: "Рим",
    name: "Rim Grand Hall",
    type: "Банкет залы",
    address: "Дарек: село Петровка, Центральная көчөсү 133",
    street: "Центральная көчөсү, 133",
    floor: "1-кабат",
    city: "с. Петровка",
    district: "Москва району, Чүй облусу",
    hours: "Күн сайын 10:00–01:00",
    rating: "4.7",
    reviews: "195",
    lat: 42.839206,
    lon: 74.055542
  },
  mapUrl: "https://2gis.kg/bishkek/firm/70000001063765710",
  mapOrgId: "70000001063765710",
  routeUrl: "https://2gis.kg/bishkek/directions/to/70000001063765710",
  telegramAlbum: "",
  music: "",
  hostsLabel: "Той ээлери",
  hosts: "Уран Назира",
  adminPin: "2026",
  rsvp: {
    pantryId: ""
  },
  ui: {
    seal: "Басыңыз",
    calendarTitle: "Сентябрь 2026",
    countdownTitle: "Тойго чейин",
    weekdays: ["Дш", "Шш", "Шр", "Бш", "Жм", "Иш", "Жк"],
    map: "2GIS картасын ачуу",
    route: "Маршрут",
    whereTitle: "Банкет залы",
    hoursLabel: "Иш убактысы",
    ratingLabel: "2GIS баасы",
    ics: "Календарга кошуу",
    formTitle: "Конок анкетасы",
    nameLabel: "Сиздин атыңыз:",
    namePh: "атыңыз",
    attendLabel: "Келе аласызбы?",
    attendYes: "Ооба, келем",
    attendPlus: "Жарым жардым менен келем",
    attendNo: "Тилекке каршы, келе албайм",
    peopleLabel: "Адам саны:",
    submit: "Жөнөтүү",
    sent: "Жөнөтүлдү",
    thanksYes: "Рахмат! Сизди күтөбүз.",
    thanksNo: "Кабарлаганыңыз үчүн рахмат.",
    saveError: "Сакталган жок. Баракты жаңыртып, кайра аракет кылыңыз.",
    sticky: "Анкетаны толтуруу"
  }
};
