/* ─────────────────────────────────────────────
   ДАННЫЕ ПРИГЛАШЕНИЯ — меняйте только здесь
   ───────────────────────────────────────────── */
window.INVITE = {
  name: "Сезим",
  event: "Кыз узатуу тоюна",
  invitedLine: "Сиздерди",
  brideLine: "Сезим кызыбыздын",
  callLine: "Чакырабыз!",
  dateISO: "2026-09-20T16:00:00",
  dateLabel: "20 сентябрь 2026",
  time: "16:00",
  day: "20",
  month: "Сентябрь",
  year: "2026",
  blessing: "Ак ниеттен, жаркын келечекке...",
  photos: {
    shyrdak: "img/shyrdak.png",
    drape: "img/drape.png",
    landscape: "img/landscape.png",
    flowers: "img/gypsophila.png",
    venue: "img/venue.jpg"
  },
  venue: {
    placeLabel: "Ресторан",
    place: "Dalida Hall",
    name: "Dalida Hall",
    type: "Банкет залы",
    address: "Дарек: Медеров көчөсү, 43, Бишкек",
    street: "Медеров көчөсү, 43",
    floor: "2 кабат",
    city: "Бишкек",
    district: "Октябрь району",
    hours: "Күн сайын 10:00–22:00",
    rating: "4.9",
    reviews: "1195",
    lat: 42.852035,
    lon: 74.624113
  },
  mapUrl: "https://2gis.kg/bishkek/firm/70000001039476658",
  mapOrgId: "70000001039476658",
  routeUrl: "https://2gis.kg/bishkek/directions/to/70000001039476658",
  telegramAlbum: "",
  music: "music.mp3",
  hostsLabel: "Той ээлери",
  hosts: "Уран Назира",
  adminPin: "2026",
  rsvp: {
    pantryId: ""
  },
  ui: {
    seal: "Басыңыз",
    calendarTitle: "Сентябрь 2026",
    countdownTitle: "Тойго чейин",
    weekdays: ["Дш", "Шш", "Шр", "Бш", "Жм", "Иш", "Жк"],
    map: "2GIS'те көрсөтүү",
    route: "Маршрутту көрсөтүү",
    whereTitle: "Банкет залы",
    hoursLabel: "Иш убактысы",
    ratingLabel: "2GIS баасы",
    ics: "Календарга кошуу",
    formTitle: "Конок анкетасы",
    nameLabel: "Сиздин атыңыз:",
    namePh: "атыңыз",
    attendLabel: "Келе аласызбы?",
    attendYes: "Ооба, келем",
    attendPlus: "Өмүрлүк жарым менен барам",
    attendNo: "Тилекке каршы, келе албайм",
    peopleLabel: "Адам саны:",
    submit: "Жөнөтүү",
    sent: "Жөнөтүлдү",
    thanksYes: "Рахмат! Сизди күтөбүз.",
    thanksNo: "Кабарлаганыңыз үчүн рахмат.",
    saveError: "Сакталган жок. Баракты жаңыртып, кайра аракет кылыңыз.",
    sticky: "Анкетаны толтуруу"
  }
};
